library(shiny)
library(shinythemes)
shinyUI(
  # Application title
  navbarPage(theme = shinytheme('darkly'),
             title = "Week 2",
             tabPanel(title = "2.1 Likelihoods",
             sidebarLayout(
              sidebarPanel(
                selectInput("plotType", "Plot Type",
                  c("Likelihood Plot" = "first", 
                    "Two Likelihood Distributions Combination" = "second",
                    "Likelihood Plot For Fixed Parameters And Different Sample Sizes" = "third",
                    "Likelihood Ratios"   = "fourth",
                    "Likelihoods of sets of studies" = "fifth")),
                  conditionalPanel(condition = "input.plotType == 'first'",
                            numericInput("n",
                                         "Number of trials:",
                                         min = 1,
                                         max = 100,
                                         value = 1,
                                         step = 1),
                            numericInput('p',
                                         'Enter the number of successes:',
                                         min = 0,
                                         max = 100,
                                         step = 1,
                                         value = 0),
                            sliderInput('v',
                                        'vertical line to help you see the maximum likelihood estimate',
                                         min = 0,
                                         max = 1,
                                         step = 0.01,
                                         value = 0),
                            checkboxInput("z",
                                          "Check to overlap the vertical line's blue point with the distribution to
                                          see the maximum likelihood estimate for theta.",
                                          value = F)
                          ),
                  conditionalPanel(condition = "input.plotType == 'second'",
                            numericInput("n1",
                                         "Number of trials (1st trial):",
                                         min = 1,
                                         max = 100,
                                         value = 1,
                                         step = 1),
                            numericInput('p1',
                                         'Enter the number of successes (1st trial):',
                                         min = 0,
                                         max = 100,
                                         step = 1,
                                         value = 0),
                            numericInput("n2",
                                         "Number of trials (2nd trial):",
                                         min = 1,
                                         max = 100,
                                         value = 1,
                                         step = 1),
                            numericInput('p2',
                                         'Enter the number of successes (2nd trial):',
                                          min = 0,
                                          max = 100,
                                          step = 1,
                                          value = 0)),
                  conditionalPanel(condition = "input.plotType == 'third'")
                            ,
                  conditionalPanel(condition = "input.plotType == 'fourth'",
                            sliderInput("u", label = HTML("Left Edge    - Number Of Successes <br/>
                                         Right Edge  - Number Of Trials"), min = 0, 
                                          max = 100, value = c(1,100)),
                            sliderInput('theta1',
                                          withMathJax(helpText('Enter \\(\\theta_{1}\\):')),
                                          min = 0,
                                          max = 1,
                                          step  = 0.01,
                                          value = 0),
                            sliderInput('theta2',
                            withMathJax(helpText('Enter \\(\\theta_{2}\\):')),
                                          min = 0,
                                          max = 1,
                                          step  = 0.01,
                                          value = 0)
                            ),
                conditionalPanel(condition = "input.plotType == 'fifth'"))
                        ,
                  mainPanel(conditionalPanel(condition = "input.plotType == 'first'",
                                 plotOutput("distPlot1"),
                                          br(),
                                          h3(textOutput('text1')),
                                          br(),
                                          uiOutput('text2'),
                                          br(),
                                          htmlOutput('text3'),
                                          br(),
                                          uiOutput('text4')),
                                  conditionalPanel(condition = "input.plotType == 'second'",
                                          plotOutput("distPlot2"),
                                          br(),
                                          htmlOutput("text5")
                                  ),
                                  conditionalPanel(condition = "input.plotType == 'third'",
                                                   plotOutput("distrPlot3"),
                                                   br(),
                                                   uiOutput('text6')
                                                   ),
                                  conditionalPanel(condition = "input.plotType == 'fourth'",
                                                   plotOutput("distrPlot4"),
                                                   br(),
                                                   uiOutput('text7'),
                                                   br(),
                                                   htmlOutput('text8')),
                                  conditionalPanel(condition = "input.plotType == 'fifth'",
                                                   uiOutput('text9'),
                                                   br(),
                                                   plotOutput('distrPlot5'),
                                                   br(),
                                                   uiOutput('text10'),
                                                   br(),
                                                   plotOutput('distrPlot6'),
                                                   br(),
                                                   uiOutput('text11'))
                                                   
                                  
                        ))),#begin second tab here
  tabPanel(title = '2.2 Bayesian Statistics',
           sidebarLayout(
             sidebarPanel(
               selectInput("course", "Part",
                           c("Bayes Factor" = "first", 
                             "Updating Our Belief" = "second",
                             "Bayesian Estimation" = "third")),
               conditionalPanel(condition = "input.course == 'first'",
                                div(style="margin-top:50.5cm",
                                textInput('Q1',
                                          'Enter the answer for Question 1 (A-D):')),
                                textInput('Q2',
                                          'Enter the answer for Question 2 (A-D):')
             ),
               conditionalPanel(condition = "input.course == 'second'"
                                ),
               conditionalPanel(condition = "input.course == 'third'")
             
             ),#sidebarlayout
           mainPanel(conditionalPanel(condition = "input.course == 'first'",
                                      uiOutput('text12'),
                                      br(),
                                      plotOutput('distrPlot7'),
                                      br(),
                                      uiOutput('text13'),
                                      plotOutput('distrPlot8')),
                     conditionalPanel(condition = "input.course == 'second'"),
                     conditionalPanel(condition = "input.course == 'third"))
           ))#here ends tabpanel
             ))
